// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgZ5U2bIjrRyMX2eSCYvPGnNCy0EuFPrA',
    appId: '1:706704206715:web:992846dfe3c71a587debde',
    messagingSenderId: '706704206715',
    projectId: 'localmart-6c37d',
    authDomain: 'localmart-6c37d.firebaseapp.com',
    storageBucket: 'localmart-6c37d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1DsUOLgmQuDC9eyOgNzK_rhkymtWWio8',
    appId: '1:706704206715:android:a2426b3e7788c9867debde',
    messagingSenderId: '706704206715',
    projectId: 'localmart-6c37d',
    storageBucket: 'localmart-6c37d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj8JexeLj57RcGzdAMEt0_yR3cwzt0_cA',
    appId: '1:706704206715:ios:3736c22c7a68b8037debde',
    messagingSenderId: '706704206715',
    projectId: 'localmart-6c37d',
    storageBucket: 'localmart-6c37d.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj8JexeLj57RcGzdAMEt0_yR3cwzt0_cA',
    appId: '1:706704206715:ios:3736c22c7a68b8037debde',
    messagingSenderId: '706704206715',
    projectId: 'localmart-6c37d',
    storageBucket: 'localmart-6c37d.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgZ5U2bIjrRyMX2eSCYvPGnNCy0EuFPrA',
    appId: '1:706704206715:web:ba0d5167b3f036817debde',
    messagingSenderId: '706704206715',
    projectId: 'localmart-6c37d',
    authDomain: 'localmart-6c37d.firebaseapp.com',
    storageBucket: 'localmart-6c37d.firebasestorage.app',
  );
}